In [19]:
import pandas as pd
import numpy as np

In [20]:
dataset = pd.read_json('../dataset/Kindle_Store_5.json', lines=True)

In [21]:
dataset

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,4,True,"07 3, 2014",A2LSKD2H9U8N0J,B000FA5KK0,{'Format:': ' Kindle Edition'},sandra sue marsolek,"pretty good story, a little exaggerated, but I...",pretty good story,1404345600,NaN,NaN
1,5,True,"05 26, 2014",A2QP13XTJND1QS,B000FA5KK0,{'Format:': ' Kindle Edition'},Tpl,"If you've read other max brand westerns, you k...",A very good book,1401062400,NaN,NaN
2,5,True,"09 16, 2016",A8WQ7MAG3HFOZ,B000FA5KK0,{'Format:': ' Kindle Edition'},Alverne F. Anderson,"Love Max, always a fun twist",Five Stars,1473984000,NaN,NaN
3,5,True,"03 3, 2016",A1E0MODSRYP7O,B000FA5KK0,{'Format:': ' Kindle Edition'},Jeff,"As usual for him, a good book",a good,1456963200,NaN,NaN
4,5,True,"09 10, 2015",AYUTCGVSM1H7T,B000FA5KK0,{'Format:': ' Kindle Edition'},DEHS - EddyRapcon,MB is one of the original western writers and ...,A Western,1441843200,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2222978,3,False,"07 16, 2016",A3Q6HJYRJX87Z9,B01HJENY3Y,{'Format:': ' Kindle Edition'},Tokea,Ok book but some parts just didn't add up I fe...,Cool book,1468627200,NaN,NaN
2222979,5,False,"07 12, 2016",A2O7HQNKCMOMUP,B01HJENY3Y,{'Format:': ' Kindle Edition'},Angela Burnett,Kia I loved this book. I am so glad that Sky ...,Crazy Read,1468281600,NaN,NaN
2222980,5,False,"07 1, 2016",A38NOWP7LQI8CM,B01HJENY3Y,{'Format:': ' Kindle Edition'},Treka22,This picks up where part one left off. Secret ...,Loved it,1467331200,NaN,NaN
2222981,5,False,"07 1, 2016",A1H9WGEEKVK0FM,B01HJENY3Y,{'Format:': ' Kindle Edition'},Adrienne Jeremiah,What a beautiful ending to such a twisted begi...,Beautiful ending,1467331200,NaN,NaN
2222982,5,True,"07 1, 2016",AGBVBXSAJDD4H,B01HJENY3Y,{'Format:': ' Kindle Edition'},Shonnikkia Francois,Honey let me tell you Ms. Kia must have been r...,Glad Tuesday received her happy ever after,1467331200,NaN,NaN

In [22]:
dataset.iloc[0,:]

overall                                                           4
verified                                                       True
reviewTime                                               07 3, 2014
reviewerID                                           A2LSKD2H9U8N0J
asin                                                     B000FA5KK0
style                                {'Format:': ' Kindle Edition'}
reviewerName                                    sandra sue marsolek
reviewText        pretty good story, a little exaggerated, but I...
summary                                           pretty good story
unixReviewTime                                           1404345600
vote                                                            NaN
image                                                           NaN
Name: 0, dtype: object

In [23]:
dataset = dataset[dataset["reviewText"].str.len() <= 200]

In [24]:
dataset

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
1,5,True,"05 26, 2014",A2QP13XTJND1QS,B000FA5KK0,{'Format:': ' Kindle Edition'},Tpl,"If you've read other max brand westerns, you k...",A very good book,1401062400,NaN,NaN
2,5,True,"09 16, 2016",A8WQ7MAG3HFOZ,B000FA5KK0,{'Format:': ' Kindle Edition'},Alverne F. Anderson,"Love Max, always a fun twist",Five Stars,1473984000,NaN,NaN
3,5,True,"03 3, 2016",A1E0MODSRYP7O,B000FA5KK0,{'Format:': ' Kindle Edition'},Jeff,"As usual for him, a good book",a good,1456963200,NaN,NaN
5,5,True,"06 14, 2015",A9DXGM6YGV14D,B000FA5KK0,{'Format:': ' Kindle Edition'},Linda DeWachter,great book,Five Stars,1434240000,NaN,NaN
7,4,True,"05 3, 2015",A12AIK6DSUF1EW,B000FA5KK0,{'Format:': ' Kindle Edition'},R. DAVIS,ALMOST BEEN TOO LONG SINCE I READ IT. GOOD REA...,ANOTHER GOOD WESTERN,1430611200,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2222970,5,False,"07 9, 2016",A1X2QS73EH0T90,B01HJCNGZ2,{'Format:': ' Kindle Edition'},M. Dumas,(7 year old's review)\n\nThey took a long time...,Cool,1468022400,NaN,NaN
2222973,5,False,"06 28, 2016",A2NLILKXV548RT,B01HJCNGZ2,{'Format:': ' Kindle Edition'},Don,So much fun! Very cute and well done. Pirates ...,So much fun!,1467072000,NaN,NaN
2222975,5,False,"03 8, 2017",A3RJ27BQRYHOWC,B01HJENY3Y,{'Format:': ' Kindle Edition'},Breona,If you haven't noticed I love Kia Meches writi...,!,1488931200,NaN,NaN
2222976,5,False,"10 24, 2016",A316WPH4MMVSHD,B01HJENY3Y,{'Format:': ' Kindle Edition'},Kindle Customer,"I liked Secret. Sky,King,Parrish. I didn't lik...",Tonya- Review,1477267200,NaN,NaN
2222977,5,False,"09 7, 2016",A1XKQXXHDI4Z7D,B01HJENY3Y,{'Format:': ' Kindle Edition'},Felicia C/O.,Both books were pretty good. I waited until re...,Poison Kisses 1and2,1473206400,NaN,NaN

In [25]:
unused_columns = [
    "verified",
    "reviewTime",
    "reviewerID",
    "asin",
    "style",
    "reviewerName",
    "summary",
    "unixReviewTime",
    "vote",
    "image"
]
dataset.drop(columns=unused_columns, inplace=True)

C:\Users\lsaid\AppData\Local\Temp\ipykernel_11308\2094714112.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.drop(columns=unused_columns, inplace=True)

In [26]:
dataset

         overall                                         reviewText
1              5  If you've read other max brand westerns, you k...
2              5                       Love Max, always a fun twist
3              5                      As usual for him, a good book
5              5                                         great book
7              4  ALMOST BEEN TOO LONG SINCE I READ IT. GOOD REA...
...          ...                                                ...
2222970        5  (7 year old's review)\n\nThey took a long time...
2222973        5  So much fun! Very cute and well done. Pirates ...
2222975        5  If you haven't noticed I love Kia Meches writi...
2222976        5  I liked Secret. Sky,King,Parrish. I didn't lik...
2222977        5  Both books were pretty good. I waited until re...

[879758 rows x 2 columns]

In [27]:
dataset[dataset["overall"] == 1]

         overall                                         reviewText
236            1          I didn't like the style or any part of it
315            1  Horrible ideas that gave killed millions if no...
322            1  I am not a fan of censorship, but this book ha...
336            1  Garbage. Author is a delusional nutjob that sh...
388            1  You are kidding right?  It was free, I was cur...
...          ...                                                ...
2222738        1  well now I know every bit of black slang on th...
2222825        1  I'm not keeping this story.  Not my type of ro...
2222828        1                                           Just no.
2222860        1  I had to quit as this was poor science fiction...
2222909        1  What a waste of time, NOTHING made sense.  It ...

[21196 rows x 2 columns]

In [28]:
dataset = dataset[[col if col != "overall" and col != "reviewText" else "overall" if col == "reviewText" else "reviewText" for col in dataset.columns]]

In [29]:
dataset

                                                reviewText  overall
1        If you've read other max brand westerns, you k...        5
2                             Love Max, always a fun twist        5
3                            As usual for him, a good book        5
5                                               great book        5
7        ALMOST BEEN TOO LONG SINCE I READ IT. GOOD REA...        4
...                                                    ...      ...
2222970  (7 year old's review)\n\nThey took a long time...        5
2222973  So much fun! Very cute and well done. Pirates ...        5
2222975  If you haven't noticed I love Kia Meches writi...        5
2222976  I liked Secret. Sky,King,Parrish. I didn't lik...        5
2222977  Both books were pretty good. I waited until re...        5

[879758 rows x 2 columns]

In [30]:
dataset.isna().sum()

reviewText    0
overall       0
dtype: int64

In [31]:
dataset[dataset["reviewText"].isna()]

Empty DataFrame
Columns: [reviewText, overall]
Index: []

In [32]:
dataset.dropna(inplace=True)

In [33]:
dataset[dataset["reviewText"].isna()]

Empty DataFrame
Columns: [reviewText, overall]
Index: []

In [34]:
from collections import Counter
sentiment_distr = Counter(dataset["overall"])
print(sentiment_distr)

Counter({5: 559925, 4: 199963, 3: 74779, 2: 23895, 1: 21196})

In [38]:
dataset.to_json('../input/dataset.json', orient='records', lines=True)